FROM python:3.12-slim

# Устанавливаем lxc клиент для управления контейнерами
RUN apt-get update && apt-get install -y \
    curl \
    ca-certificates \
    snapd \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

COPY . .

CMD ["uvicorn", "app.main:app", "--host", "0.0.0.0", "--port", "8000", "--reload"]