upstream backend { 
    server backend:8000; 
} 

upstream frontend { 
    server frontend:5173; 
} 

server { 
    listen 80; 

    # приоритетный маршрут для WebSocket-соединений API
    location /api/v1/ws/ { 
        proxy_pass http://backend; 
        proxy_http_version 1.1; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "upgrade"; 
        proxy_set_header Host $host; 
        proxy_read_timeout 3600s; 
        proxy_send_timeout 3600s; 
    } 

    # маршрут для остального API
    location /api/ { 
        proxy_pass http://backend; 
        proxy_set_header Host $host; 
        proxy_set_header X-Real-IP $remote_addr; 
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for; 
    } 

    # фронтенд и его внутренний WebSocket (например, для Hot Module Replacement)
    location / { 
        proxy_pass http://frontend; 
        proxy_http_version 1.1; 
        proxy_set_header Upgrade $http_upgrade; 
        proxy_set_header Connection "upgrade"; 
        proxy_set_header Host $host; 
    } 
}